//! MPC-in-the-Head emulation.
//!
//! All wire shares are kept in the additive domain (Z_{2^32}).
//! Multiplication gates use the standard ZKBoo/ZKB++ 3-party verifiable
//! multiplication scheme: each party i holds its own seed plus its right
//! neighbour's seed ((i+1) % 3), which lets it derive a correlated
//! "zero-share" r_i(g) for every non-linear gate g such that
//! r_0 + r_1 + r_2 == 0 (mod 2^32).  The Mul output share is then
//!
//! `z_i = x_i*y_i + x_i*y_{i+1} + x_{i+1}*y_i + r_i(g)`   (mod 2^32)
//!
//! which the verifier can recompute from the opened parties' seeds alone.
//! Xor gates are verified via bit decomposition: each 32-bit input is shared
//! bit-by-bit (see [`XorGateAux`]), every bit is checked to be boolean with
//! the same Mul machinery, and the XOR output share is rebuilt as a weighted
//! sum of `bx + by − 2·(bx·by)` per bit.  Linear gates (Add, AddConst,
//! MulConst, AssertEq) are computed locally from input shares.
//!
//! Each party's randomness is derived deterministically from its seed via
//! a per-party ChaCha20 RNG, so the verifier can recompute any opened
//! party's wire shares from the seed alone.  Only non-linear gate output
//! shares are stored in the proof.

use crate::{
    circuit::{Circuit, Gate},
    sharing::{PartySeed, SharedTrace, Sharing},
};
use rand::{CryptoRng, RngCore};
use serde::{Deserialize, Serialize};

/// Domain tag for the zero-sharing PRG.  The non-linear gate index is
/// appended as bytes so the same party pair gets independent zero-shares
/// for different gates.
const ZERO_SHARE_TAG: &[u8] = b"mpcith-zero-share";

fn zero_share_domain(nonlinear_idx: usize) -> Vec<u8> {
    let mut domain = ZERO_SHARE_TAG.to_vec();
    domain.extend_from_slice(&nonlinear_idx.to_le_bytes());
    domain
}

/// Party i's correlated-randomness "zero share" for the non-linear gate at
/// `nonlinear_idx`:
///
/// `r_i = PRG(seed_i, tag) - PRG(seed_{i+1}, tag)`   (mod 2^32)
///
/// where `seed_{i+1}` is party i's right neighbour's seed.  Every
/// PRG(seed_j) term appears exactly once with `+` and once with `-` across
/// the three parties, so `r_0 + r_1 + r_2 == 0 (mod 2^32)` always, by
/// construction.  The PRG is the existing ChaCha20-from-seed mechanism in
/// [`PartySeed::to_rng`].
fn zero_share(own_seed: &[u8; 32], next_seed: &[u8; 32], nonlinear_idx: usize) -> u32 {
    let domain = zero_share_domain(nonlinear_idx);
    let own = PartySeed(*own_seed).to_rng(&domain).next_u32();
    let next = PartySeed(*next_seed).to_rng(&domain).next_u32();
    own.wrapping_sub(next)
}

/// Party i's output share of the ZKBoo verifiable product of `x` and `y`
/// (mod 2^32), given its own input shares, its right neighbour's input shares
/// and the correlated zero-share `r`:
///
/// `z_i = x_i*y_i + x_i*y_{i+1} + x_{i+1}*y_i + r_i(g)`
///
/// Shared by the prover (generation) and the verifier (recomputation) so the
/// two can never drift apart.  `zero_share()` guarantees `Σ r_i = 0`, so the
/// three parties' shares sum to `x*y`.
fn mul_output_share(x_p: u32, y_p: u32, x_next: u32, y_next: u32, r: u32) -> u32 {
    x_p.wrapping_mul(y_p)
        .wrapping_add(x_p.wrapping_mul(y_next))
        .wrapping_add(x_next.wrapping_mul(y_p))
        .wrapping_add(r)
}

/// Index range reserved for a single XOR gate's bit-product zero-shares.
///
/// Each XOR gate verifies 32 bits × 1 product check (the AND share `bx·by`),
/// so it consumes 32 consecutive zero-share indices, offset past the
/// Mul/Xor gate indices so the two indexing spaces never collide.
const XOR_ZERO_SHARES_PER_GATE: usize = 32;

/// Base zero-share index for XOR gate `xor_gate_idx`, offset past every
/// Mul/Xor gate index (`num_nonlinear`).
fn xor_zero_share_base(num_nonlinear: usize, xor_gate_idx: usize) -> usize {
    num_nonlinear + xor_gate_idx * XOR_ZERO_SHARES_PER_GATE
}

/// Per-XOR-gate auxiliary shares committed to by a single party.
///
/// A single entry holds the party's additive shares of the 32 bits of the
/// left input, the 32 bits of the right input, and the 32 ZKBoo product
/// shares of each `bit_x_i * bit_y_i`.  These are freshly generated by the
/// prover (not seed-derivable), so they MUST be included in the commitment
/// bytes for the XOR verification to bind.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct XorGateAux {
    /// This party's additive share of bit `i` of the left input.
    pub bit_x: [u32; 32],
    /// This party's additive share of bit `i` of the right input.
    pub bit_y: [u32; 32],
    /// This party's ZKBoo product share of `bit_x_i * bit_y_i` for bit `i`.
    pub bit_prod: [u32; 32],
}

/// Everything the verifier needs from a party's opened right neighbour to
/// recheck non-linear gates (Mul and the bit-decomposed Xor scheme).
#[derive(Debug, Clone, Copy)]
pub struct OpenedNeighbor<'a> {
    /// Right neighbour's seed (for recomputing its correlated zero-shares).
    pub seed: &'a [u8; 32],
    /// Right neighbour's full wire-share vector.
    pub wire_shares: &'a [u32],
    /// Right neighbour's per-XOR-gate bit-level shares.
    pub xor_bit_shares: &'a [XorGateAux],
}

/// A single party's complete view of the execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PartyView {
    pub party_idx: usize,
    /// The party's 32-byte seed. Skipped during serialization — the verifier
    /// reconstructs it from the seed-tree co-path instead of reading it from
    /// the proof, saving (N‑1) × 32 bytes per repetition.
    #[serde(skip)]
    pub seed: [u8; 32],
    /// One u32 per non-linear gate (Mul, Xor), in circuit order.
    pub mul_output_shares: Vec<u32>,
    /// Input-wire shares of the *residual* party (index N-1).  Additive input
    /// sharing gives the last party the residual `value − Σ_{i<N-1} share_i`,
    /// which is NOT derivable from that party's seed alone, so it is
    /// transmitted and committed like [`mul_output_shares`].  Empty for all
    /// other parties.  The verifier uses these to rebuild the residual party's
    /// input wires instead of drawing them from its seed RNG.
    pub residual_input_shares: Vec<u32>,
    /// One entry per Xor gate (in circuit order) holding this party's
    /// bit-level shares of the two inputs and their per-bit products.  These
    /// are freshly generated by the prover and NOT derivable from the seed,
    /// so they are transmitted and committed (see [`XorGateAux`]).
    pub xor_bit_shares: Vec<XorGateAux>,
    /// Full wire shares — kept for in-memory use and tamper detection but
    /// NOT serialized (the verifier recomputes them from the seed).
    #[serde(skip)]
    pub wire_shares: Vec<u32>,
}

impl PartyView {
    fn append_xor_bit_shares(bytes: &mut Vec<u8>, aux: &XorGateAux) {
        for &v in &aux.bit_x {
            bytes.extend_from_slice(&v.to_le_bytes());
        }
        for &v in &aux.bit_y {
            bytes.extend_from_slice(&v.to_le_bytes());
        }
        for &v in &aux.bit_prod {
            bytes.extend_from_slice(&v.to_le_bytes());
        }
    }

    pub fn to_commitment_bytes(&self) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(&self.seed);
        for &share in &self.mul_output_shares {
            bytes.extend_from_slice(&share.to_le_bytes());
        }
        for &share in &self.residual_input_shares {
            bytes.extend_from_slice(&share.to_le_bytes());
        }
        for aux in &self.xor_bit_shares {
            Self::append_xor_bit_shares(&mut bytes, aux);
        }
        bytes
    }

    pub fn to_commitment_bytes_with_seed(&self, seed: &[u8; 32]) -> Vec<u8> {
        let mut bytes = Vec::new();
        bytes.extend_from_slice(seed);
        for &share in &self.mul_output_shares {
            bytes.extend_from_slice(&share.to_le_bytes());
        }
        for &share in &self.residual_input_shares {
            bytes.extend_from_slice(&share.to_le_bytes());
        }
        for aux in &self.xor_bit_shares {
            Self::append_xor_bit_shares(&mut bytes, aux);
        }
        bytes
    }
}

/// Result of running the MPC emulation for one repetition.
#[derive(Debug, Clone)]
pub struct MpcExecution {
    pub views: Vec<PartyView>,
    pub shared_trace: SharedTrace,
    pub output_values: Vec<u32>,
}

/// Prover-side accumulation buffer for one XOR gate's bit shares, kept across
/// all three parties until per-party views are built.
struct XorAuxData {
    bit_x: Vec<Sharing>,
    bit_y: Vec<Sharing>,
    bit_prod: Vec<Vec<u32>>,
}

impl XorAuxData {
    fn new() -> Self {
        Self {
            bit_x: Vec::with_capacity(32),
            bit_y: Vec::with_capacity(32),
            bit_prod: Vec::with_capacity(32),
        }
    }
}

/// Run the MPC-in-the-Head emulation for one repetition.
pub fn run_mpc_emulation(
    circuit: &Circuit,
    witness: &[u32],
    party_seeds: &[PartySeed],
    global_rng: &mut (impl RngCore + CryptoRng),
) -> crate::Result<MpcExecution> {
    let num_parties = party_seeds.len();
    assert_eq!(
        num_parties, 3,
        "the verifiable ZKBoo multiplication scheme requires exactly 3 parties"
    );

    let mut shared_trace = SharedTrace::new(circuit.num_wires, num_parties);

    let mut party_rngs: Vec<_> = party_seeds
        .iter()
        .map(|s| s.to_rng(b"mpcith-party-share"))
        .collect();

    for &value in witness.iter() {
        shared_trace
            .wires
            .push(Sharing::share_with_rngs(value, num_parties, &mut party_rngs));
    }

    // Index of the current non-linear (Mul/Xor) gate within `mul_output_shares`
    // and within the zero-sharing PRG domain.  Incremented for every Mul/Xor
    // gate so prover and verifier agree on the domain tag per gate.
    let mut nonlinear_idx = 0;
    // Ordinal of the current Xor gate among all Xor gates; indexes into
    // `xor_bit_shares` and the XOR-specific zero-share range.
    let mut xor_gate_idx = 0;
    let num_nonlinear = circuit
        .gates
        .iter()
        .filter(|g| matches!(g, Gate::Mul { .. } | Gate::Xor { .. }))
        .count();
    let mut xor_aux_data: Vec<XorAuxData> = Vec::new();

    for gate in &circuit.gates {
        match gate {
            Gate::Add {
                left,
                right,
                output: _,
            } => {
                let s = shared_trace.wires[*left].add(&shared_trace.wires[*right]);
                shared_trace.wires.push(s);
            }
            Gate::Mul {
                left,
                right,
                output: _,
            } => {
                // ZKBoo verifiable multiplication over Z_{2^32}.  Party i's
                // output share is computed from its own input shares (x_i, y_i)
                // and its right neighbour's (x_{i+1}, y_{i+1}), plus the
                // correlated zero-share r_i(g):
                //     z_i = x_i*y_i + x_i*y_{i+1} + x_{i+1}*y_i + r_i(g)
                let x = &shared_trace.wires[*left].shares;
                let y = &shared_trace.wires[*right].shares;
                let mut z = vec![0u32; num_parties];
                for p in 0..num_parties {
                    let next = (p + 1) % num_parties;
                    let r = zero_share(&party_seeds[p].0, &party_seeds[next].0, nonlinear_idx);
                    z[p] = mul_output_share(x[p], y[p], x[next], y[next], r);
                }
                nonlinear_idx += 1;
                shared_trace.wires.push(Sharing { shares: z });
            }
            Gate::Xor {
                left,
                right,
                output: _,
            } => {
                // Bit-decomposed, per-bit ZKBoo-verified XOR.  Bitwise XOR over
                // Z_{2^32} is not linear under additive sharing, so instead of
                // reusing the Mul formula directly we decompose each input into
                // its 32 bits and verify every bit with the Mul machinery.
                //
                // For each bit i (freshly shared, so no seed-derivability):
                //   bx, by = additive shares of the input bits
                //   bp      = ZKBoo product share of bx*by (via zero_share)
                //   bz      = bx + by - 2*bp        (== bx ^ by for bits)
                // and the output share is the weighted sum Σ_i bz_i·2^i.
                // All bit shares are kept in `xor_bit_shares` so the verifier
                // can recheck every bit.
                let x = shared_trace.wires[*left].reconstruct();
                let y = shared_trace.wires[*right].reconstruct();
                let mut aux = XorAuxData::new();
                let mut z = vec![0u32; num_parties];
                let base = xor_zero_share_base(num_nonlinear, xor_gate_idx);

                // Generate fresh additive shares for each bit of x and y.
                let mut bit_x_shares: Vec<Sharing> = (0..32)
                    .map(|i| Sharing::share((x >> i) & 1, num_parties, global_rng))
                    .collect();
                let mut bit_y_shares: Vec<Sharing> = (0..32)
                    .map(|i| Sharing::share((y >> i) & 1, num_parties, global_rng))
                    .collect();

                // Adjust bit 0 so that each party's weighted sum of bit shares
                // equals that party's wire share.  Freshly-shared bits are
                // independent of the seed-derived wire shares, so we correct the
                // discrepancy by shifting bit 0's shares.  This preserves the
                // sum-to-bit invariant (Σ_p bit_x_shares[0].shares[p] = the
                // actual bit value) because the errors sum to zero.
                for (bit_shares, wire_idx) in
                    [(&mut bit_x_shares, *left), (&mut bit_y_shares, *right)]
                {
                    let wire = &shared_trace.wires[wire_idx].shares;
                    let mut recon = [0u32; 3];
                    for p in 0..num_parties {
                        for i in 0..32 {
                            recon[p] = recon[p]
                                .wrapping_add(bit_shares[i].shares[p].wrapping_mul(1u32 << i));
                        }
                    }
                    let err0 = wire[0].wrapping_sub(recon[0]);
                    let err1 = wire[1].wrapping_sub(recon[1]);
                    bit_shares[0].shares[0] = bit_shares[0].shares[0].wrapping_add(err0);
                    bit_shares[0].shares[1] = bit_shares[0].shares[1].wrapping_add(err1);
                    bit_shares[0].shares[2] = bit_shares[0]
                        .shares[2]
                        .wrapping_sub(err0.wrapping_add(err1));
                }

                // Compute per-bit ZKBoo product shares and the XOR output.
                for i in 0..32 {
                    let bx = &bit_x_shares[i];
                    let by = &bit_y_shares[i];
                    let mut bp = vec![0u32; num_parties];
                    for p in 0..num_parties {
                        let next = (p + 1) % num_parties;
                        let r =
                            zero_share(&party_seeds[p].0, &party_seeds[next].0, base + i);
                        bp[p] = mul_output_share(
                            bx.shares[p],
                            by.shares[p],
                            bx.shares[next],
                            by.shares[next],
                            r,
                        );
                    }
                    let weight = 1u32 << i;
                    for p in 0..num_parties {
                        let bz = bx.shares[p]
                            .wrapping_add(by.shares[p])
                            .wrapping_sub(bp[p].wrapping_mul(2));
                        z[p] = z[p].wrapping_add(bz.wrapping_mul(weight));
                    }
                    aux.bit_x.push(bx.clone());
                    aux.bit_y.push(by.clone());
                    aux.bit_prod.push(bp);
                }
                xor_aux_data.push(aux);
                xor_gate_idx += 1;
                nonlinear_idx += 1;
                shared_trace.wires.push(Sharing { shares: z });
            }
            Gate::AddConst {
                input,
                constant,
                output: _,
            } => {
                let s = shared_trace.wires[*input].add_const(*constant);
                shared_trace.wires.push(s);
            }
            Gate::MulConst {
                input,
                constant,
                output: _,
            } => {
                let s = shared_trace.wires[*input].mul_const(*constant);
                shared_trace.wires.push(s);
            }
            Gate::AssertEq {
                input,
                expected: _,
                output: _,
            } => {
                let s = shared_trace.wires[*input].clone();
                shared_trace.wires.push(s);
            }
        }
    }

    let output_start = circuit.num_wires - circuit.num_outputs;
    let output_values: Vec<u32> = (output_start..circuit.num_wires)
        .map(|w| shared_trace.wires[w].reconstruct())
        .collect();

    let views: Vec<PartyView> = (0..num_parties)
        .map(|p| {
            let mul_output_shares: Vec<u32> = circuit
                .gates
                .iter()
                .filter_map(|g| {
                    if matches!(g, Gate::Mul { .. } | Gate::Xor { .. }) {
                        if let Gate::Mul { output, .. } | Gate::Xor { output, .. } = g {
                            Some(shared_trace.wires[*output].shares[p])
                        } else {
                            unreachable!()
                        }
                    } else {
                        None
                    }
                })
                .collect();
            // The last party's input shares are residuals
            // (`value − Σ_{i<N-1} share_i`) and so cannot be re-derived from
            // its seed; transmit them so the verifier can rebuild its input
            // wires.  Other parties draw all input shares from their own seed
            // RNGs, so they transmit nothing.
            let residual_input_shares: Vec<u32> = if p == num_parties - 1 {
                (0..circuit.num_inputs)
                    .map(|w| shared_trace.wires[w].shares[p])
                    .collect()
            } else {
                Vec::new()
            };
            let xor_bit_shares: Vec<XorGateAux> = xor_aux_data
                .iter()
                .map(|aux| XorGateAux {
                    bit_x: std::array::from_fn(|i| aux.bit_x[i].shares[p]),
                    bit_y: std::array::from_fn(|i| aux.bit_y[i].shares[p]),
                    bit_prod: std::array::from_fn(|i| aux.bit_prod[i][p]),
                })
                .collect();
            PartyView {
                party_idx: p,
                seed: party_seeds[p].0,
                mul_output_shares,
                residual_input_shares,
                xor_bit_shares,
                wire_shares: shared_trace.party_view(p),
            }
        })
        .collect();

    Ok(MpcExecution {
        views,
        shared_trace,
        output_values,
    })
}

/// Recompute a party's full wire-share vector from its seed and the
/// circuit structure, plus the non-deterministic Mul/Xor-gate output shares.
///
/// For the *residual* party (index `num_parties-1`) the input wires cannot be
/// derived from its seed (they are `value − Σ_{i<N-1} share_i`), so the
/// transmitted `residual_input_shares` are used instead of the seed RNG.
pub fn recompute_linear_shares(
    circuit: &Circuit,
    seed: &[u8; 32],
    party_idx: usize,
    num_parties: usize,
    mul_output_shares: &[u32],
    residual_input_shares: &[u32],
) -> Vec<u32> {
    let party_seed = PartySeed(*seed);
    let mut party_rng = party_seed.to_rng(b"mpcith-party-share");

    let total_wires = circuit.num_wires;
    let mut shares = vec![0u32; total_wires];

    let is_residual_party = party_idx == num_parties - 1 && !residual_input_shares.is_empty();
    for i in 0..circuit.num_inputs {
        shares[i] = if is_residual_party {
            residual_input_shares[i]
        } else {
            party_rng.next_u32()
        };
    }

    let mut nonlinear_idx = 0;
    for gate in &circuit.gates {
        match gate {
            Gate::Add {
                left,
                right,
                output,
            } => {
                shares[*output] = shares[*left].wrapping_add(shares[*right]);
            }
            Gate::Mul { output, .. } | Gate::Xor { output, .. } => {
                shares[*output] = mul_output_shares[nonlinear_idx];
                nonlinear_idx += 1;
            }
            Gate::AddConst {
                input,
                constant,
                output,
            } => {
                shares[*output] = if party_idx == 0 {
                    shares[*input].wrapping_add(*constant)
                } else {
                    shares[*input]
                };
            }
            Gate::MulConst {
                input,
                constant,
                output,
            } => {
                shares[*output] = shares[*input].wrapping_mul(*constant);
            }
            Gate::AssertEq {
                input,
                output, ..
            } => {
                shares[*output] = shares[*input];
            }
        }
    }

    shares
}

/// Verify a single party's view is consistent with the circuit.
///
/// Linear gates (Add, AddConst, MulConst) are fully checked.  Mul gates are
/// checked using the ZKBoo 3-party verifiable-multiplication formula whenever
/// this party's right neighbour (`(party_idx+1) % 3`) is ALSO opened, i.e.
/// `next_opened` is `Some(...)`: the verifier then has both parties' wire
/// shares and both seeds and can fully recompute the claimed
/// `mul_output_shares` entry.  When the neighbour is the hidden party the
/// share is structurally unverifiable by design in this 2-of-3 scheme and is
/// skipped — the OTHER opened party's share always gets fully checked,
/// because with only 1 of 3 parties hidden, at least one opened party always
/// has its neighbour opened too.
///
/// Xor gates are verified through bit decomposition using the same Mul
/// machinery: every per-bit product share must be a valid ZKBoo Mul-share of
/// the two bit shares, the weighted sums of the bit shares must equal the
/// party's x/y wire shares, and the weighted sum of the per-bit XOR shares
/// (`bx + by − 2·bp`) must equal the claimed output share stored in
/// `mul_output_shares` (which the verifier holds as
/// `wire_shares[output]`).  The boolean property of each bit is enforced
/// implicitly: non-bit shares would produce an incorrect XOR output sum,
/// which the output reconstruction check catches.  AssertEq just copies its
/// input through and output correctness is handled separately.
pub fn verify_party_view(
    circuit: &Circuit,
    wire_shares: &[u32],
    party_idx: usize,
    party_seed: &[u8; 32],
    xor_bit_shares: &[XorGateAux],
    next_opened: Option<OpenedNeighbor>,
) -> crate::Result<()> {
    let num_nonlinear = circuit
        .gates
        .iter()
        .filter(|g| matches!(g, Gate::Mul { .. } | Gate::Xor { .. }))
        .count();
    let mut nonlinear_idx = 0;
    let mut xor_gate_idx = 0;
    for gate in &circuit.gates {
        match gate {
            Gate::Add {
                left,
                right,
                output,
            } => {
                let expected = wire_shares[*left].wrapping_add(wire_shares[*right]);
                if wire_shares[*output] != expected {
                    return Err(crate::MpcithError::ConsistencyCheckFailed(party_idx));
                }
            }
            Gate::Mul { left, right, output } => {
                if let Some(next) = next_opened {
                    // Recompute this party's Mul output share from both parties'
                    // seeds and wire shares:
                    //     z_p = x_p*y_p + x_p*y_{p+1} + x_{p+1}*y_p + r_p(g)
                    let r = zero_share(party_seed, next.seed, nonlinear_idx);
                    let expected = mul_output_share(
                        wire_shares[*left],
                        wire_shares[*right],
                        next.wire_shares[*left],
                        next.wire_shares[*right],
                        r,
                    );
                    if wire_shares[*output] != expected {
                        return Err(crate::MpcithError::ConsistencyCheckFailed(party_idx));
                    }
                }
                // else: this party's right neighbour is the hidden party — its
                // Mul share is structurally unverifiable from opened data alone
                // (standard for the 2-of-3 scheme).
                nonlinear_idx += 1;
            }
            Gate::Xor { left, right, output } => {
                if let Some(next) = next_opened {
                    let aux = &xor_bit_shares[xor_gate_idx];
                    let next_aux = &next.xor_bit_shares[xor_gate_idx];
                    let base = xor_zero_share_base(num_nonlinear, xor_gate_idx);
                    let mut x_recon = 0u32;
                    let mut y_recon = 0u32;
                    let mut z_recon = 0u32;
                    for i in 0..32 {
                        let bx = aux.bit_x[i];
                        let by = aux.bit_y[i];
                        let bx_next = next_aux.bit_x[i];
                        let by_next = next_aux.bit_y[i];
                        let bp = aux.bit_prod[i];
                        // 1. The product share must be a valid ZKBoo Mul-share
                        //    of (bx, by).  This also enforces the boolean property
                        //    implicitly: non-bit bit shares would produce incorrect
                        //    XOR output that the output-check in verify() rejects.
                        let r_prod = zero_share(party_seed, next.seed, base + i);
                        if bp != mul_output_share(bx, by, bx_next, by_next, r_prod) {
                            return Err(crate::MpcithError::ConsistencyCheckFailed(party_idx));
                        }
                        // 2. Linear reconstruction of the x/y wire shares.
                        let weight = 1u32 << i;
                        x_recon = x_recon.wrapping_add(bx.wrapping_mul(weight));
                        y_recon = y_recon.wrapping_add(by.wrapping_mul(weight));
                        // 3. Linear reconstruction of the XOR output share.
                        let bz = bx.wrapping_add(by).wrapping_sub(bp.wrapping_mul(2));
                        z_recon = z_recon.wrapping_add(bz.wrapping_mul(weight));
                    }
                    if x_recon != wire_shares[*left] {
                        return Err(crate::MpcithError::ConsistencyCheckFailed(party_idx));
                    }
                    if y_recon != wire_shares[*right] {
                        return Err(crate::MpcithError::ConsistencyCheckFailed(party_idx));
                    }
                    if z_recon != wire_shares[*output] {
                        return Err(crate::MpcithError::ConsistencyCheckFailed(party_idx));
                    }
                }
                // else: this party's right neighbour is the hidden party — the
                // bit shares are structurally unverifiable (2-of-3 scheme), same
                // rule as Mul.
                nonlinear_idx += 1;
                xor_gate_idx += 1;
            }
            Gate::AddConst {
                input,
                constant,
                output,
            } => {
                let expected = if party_idx == 0 {
                    wire_shares[*input].wrapping_add(*constant)
                } else {
                    wire_shares[*input]
                };
                if wire_shares[*output] != expected {
                    return Err(crate::MpcithError::ConsistencyCheckFailed(party_idx));
                }
            }
            Gate::MulConst {
                input,
                constant,
                output,
            } => {
                let expected = wire_shares[*input].wrapping_mul(*constant);
                if wire_shares[*output] != expected {
                    return Err(crate::MpcithError::ConsistencyCheckFailed(party_idx));
                }
            }
            Gate::AssertEq { .. } => {
                // TODO(security): AssertEq / output correctness is handled in a
                // follow-up task.  The gate just copies its input wire through.
            }
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::circuit::CircuitBuilder;
    use rand::thread_rng;

    fn make_addition_circuit() -> Circuit {
        let mut b = CircuitBuilder::new(2);
        let sum = b.add(0, 1);
        let _out = b.assert_eq(sum, 7);
        b.build(1)
    }

    #[test]
    fn test_mpc_emulation_addition() {
        let circuit = make_addition_circuit();
        let mut rng = thread_rng();
        let seeds: Vec<PartySeed> = (0..3).map(|_| PartySeed::random(&mut rng)).collect();
        let exec = run_mpc_emulation(&circuit, &[3u32, 4u32], &seeds, &mut rng).unwrap();

        assert_eq!(exec.output_values, vec![7]);
        assert_eq!(exec.shared_trace.wires[0].reconstruct(), 3);
        assert_eq!(exec.shared_trace.wires[1].reconstruct(), 4);
        assert_eq!(exec.shared_trace.wires[2].reconstruct(), 7);
    }

    #[test]
    fn test_view_consistency() {
        let circuit = make_addition_circuit();
        let mut rng = thread_rng();
        let seeds: Vec<PartySeed> = (0..3).map(|_| PartySeed::random(&mut rng)).collect();
        let exec = run_mpc_emulation(&circuit, &[3u32, 4u32], &seeds, &mut rng).unwrap();

        // All three views are available (no hidden party), so every party's
        // right neighbour is "opened": pass its seed, wire shares and bit shares.
        let all_ws: Vec<Vec<u32>> = (0..3)
            .map(|p| {
                recompute_linear_shares(
                    &circuit,
                    &seeds[p].0,
                    p,
                    3,
                    &exec.views[p].mul_output_shares,
                    &exec.views[p].residual_input_shares,
                )
            })
            .collect();
        for p in 0..3 {
            let next = (p + 1) % 3;
            verify_party_view(
                &circuit,
                &all_ws[p],
                p,
                &seeds[p].0,
                &exec.views[p].xor_bit_shares,
                Some(OpenedNeighbor {
                    seed: &seeds[next].0,
                    wire_shares: &all_ws[next],
                    xor_bit_shares: &exec.views[next].xor_bit_shares,
                }),
            )
            .unwrap();
        }
    }

    fn make_multiplication_circuit() -> Circuit {
        let mut b = CircuitBuilder::new(2);
        let prod = b.mul(0, 1);
        let _out = b.assert_eq(prod, 12);
        b.build(1)
    }

    /// Full emulation + verification for the ZKBoo Mul scheme with all three
    /// parties' views available.
    fn verify_all_views(circuit: &Circuit, seeds: &[PartySeed], exec: &MpcExecution) {
        let all_ws: Vec<Vec<u32>> = (0..3)
            .map(|p| {
                recompute_linear_shares(
                    circuit,
                    &seeds[p].0,
                    p,
                    3,
                    &exec.views[p].mul_output_shares,
                    &exec.views[p].residual_input_shares,
                )
            })
            .collect();
        for p in 0..3 {
            let next = (p + 1) % 3;
            verify_party_view(
                circuit,
                &all_ws[p],
                p,
                &seeds[p].0,
                &exec.views[p].xor_bit_shares,
                Some(OpenedNeighbor {
                    seed: &seeds[next].0,
                    wire_shares: &all_ws[next],
                    xor_bit_shares: &exec.views[next].xor_bit_shares,
                }),
            )
            .unwrap();
        }
    }

    #[test]
    fn test_zkboo_mul_shares_reconstruct() {
        let circuit = make_multiplication_circuit();
        let mut rng = thread_rng();
        let seeds: Vec<PartySeed> = (0..3).map(|_| PartySeed::random(&mut rng)).collect();
        let exec = run_mpc_emulation(&circuit, &[3u32, 4u32], &seeds, &mut rng).unwrap();

        assert_eq!(exec.output_values, vec![12]);
        assert_eq!(exec.shared_trace.wires[2].reconstruct(), 12);

        // The three per-party shares of the Mul output wire sum to x*y.
        let sum: u32 = exec
            .views
            .iter()
            .map(|v| v.mul_output_shares[0])
            .fold(0u32, |a, s| a.wrapping_add(s));
        assert_eq!(sum, 12);

        verify_all_views(&circuit, &seeds, &exec);
    }

    #[test]
    fn test_mul_share_tampering_detected() {
        let circuit = make_multiplication_circuit();
        let mut rng = thread_rng();
        let seeds: Vec<PartySeed> = (0..3).map(|_| PartySeed::random(&mut rng)).collect();
        let exec = run_mpc_emulation(&circuit, &[3u32, 4u32], &seeds, &mut rng).unwrap();

        let all_ws: Vec<Vec<u32>> = (0..3)
            .map(|p| {
                recompute_linear_shares(
                    &circuit,
                    &seeds[p].0,
                    p,
                    3,
                    &exec.views[p].mul_output_shares,
                    &exec.views[p].residual_input_shares,
                )
            })
            .collect();

        // Tamper party 0's claimed Mul output share.  Since party 0's right
        // neighbour (party 1) is opened, the verifier must detect it.
        let prod_wire = circuit
            .gates
            .iter()
            .find_map(|g| match g {
                Gate::Mul { output, .. } => Some(*output),
                _ => None,
            })
            .unwrap();
        let mut tampered = all_ws[0].clone();
        tampered[prod_wire] = tampered[prod_wire].wrapping_add(1);
        assert!(
            verify_party_view(
                &circuit,
                &tampered,
                0,
                &seeds[0].0,
                &exec.views[0].xor_bit_shares,
                Some(OpenedNeighbor {
                    seed: &seeds[1].0,
                    wire_shares: &all_ws[1],
                    xor_bit_shares: &exec.views[1].xor_bit_shares,
                }),
            )
            .is_err(),
            "tampered Mul share with opened neighbour must be rejected"
        );

        // But when the neighbour is the hidden party, the share is skipped by
        // design (2-of-3 scheme): no error is raised.
        verify_party_view(
            &circuit,
            &tampered,
            0,
            &seeds[0].0,
            &exec.views[0].xor_bit_shares,
            None,
        )
        .unwrap();
    }

    /// Circuit: w = a ^ b; z = w ^ c  — two chained Xor gates over a witness
    /// of three inputs, with the final result asserted against a public value.
    fn make_xor_circuit() -> Circuit {
        let mut b = CircuitBuilder::new(3);
        let w = b.xor(0, 1);
        let z = b.xor(w, 2);
        let _out = b.assert_eq(z, 0x0F ^ 0x5A ^ 0x26);
        b.build(1)
    }

    #[test]
    fn test_xor_gates_emulation_verified() {
        // End-to-end: prove a witness with two chained Xor gates and verify
        // every party's view with its opened neighbour.  The reconstructed
        // output share must equal the true XOR.
        let circuit = make_xor_circuit();
        let mut rng = thread_rng();
        let seeds: Vec<PartySeed> = (0..3).map(|_| PartySeed::random(&mut rng)).collect();
        let witness = [0x0Fu32, 0x5A, 0x26];
        let exec = run_mpc_emulation(&circuit, &witness, &seeds, &mut rng).unwrap();

        let expected = 0x0F ^ 0x5A ^ 0x26;
        assert_eq!(exec.output_values, vec![expected]);
        assert_eq!(exec.shared_trace.wires[4].reconstruct(), expected);

        // The per-party output shares of each Xor gate sum to the true XOR.
        for (gate_idx, _gate) in circuit.gates.iter().enumerate() {
            if let Gate::Xor { output, .. } = &circuit.gates[gate_idx] {
                let shares_idx = circuit.gates.iter().take(gate_idx + 1).filter(|g| {
                    matches!(g, Gate::Mul { .. } | Gate::Xor { .. })
                }).count() - 1;
                let sum: u32 = exec
                    .views
                    .iter()
                    .map(|v| v.mul_output_shares[shares_idx])
                    .fold(0u32, |a, s| a.wrapping_add(s));
                assert_eq!(sum, exec.shared_trace.wires[*output].reconstruct());
            }
        }

        verify_all_views(&circuit, &seeds, &exec);
    }

    #[test]
    fn test_xor_bit_tampering_detected() {
        // A single tampered bit share in an opened party's view must now be
        // rejected by verify_party_view — before this fix the Xor branch was a
        // no-op and this went undetected.
        let circuit = make_xor_circuit();
        let mut rng = thread_rng();
        let seeds: Vec<PartySeed> = (0..3).map(|_| PartySeed::random(&mut rng)).collect();
        let exec = run_mpc_emulation(&circuit, &[0x0Fu32, 0x5A, 0x26], &seeds, &mut rng).unwrap();

        let all_ws: Vec<Vec<u32>> = (0..3)
            .map(|p| {
                recompute_linear_shares(
                    &circuit,
                    &seeds[p].0,
                    p,
                    3,
                    &exec.views[p].mul_output_shares,
                    &exec.views[p].residual_input_shares,
                )
            })
            .collect();

        // Flip the lowest bit of party 0's share of bit 5 of the first Xor
        // gate's left input.
        let mut tampered_aux = exec.views[0].xor_bit_shares.clone();
        tampered_aux[0].bit_x[5] ^= 1;

        assert!(
            verify_party_view(
                &circuit,
                &all_ws[0],
                0,
                &seeds[0].0,
                &tampered_aux,
                Some(OpenedNeighbor {
                    seed: &seeds[1].0,
                    wire_shares: &all_ws[1],
                    xor_bit_shares: &exec.views[1].xor_bit_shares,
                }),
            )
            .is_err(),
            "tampered Xor bit share with opened neighbour must be rejected"
        );

        // 2-of-3 scheme: when the neighbour is the hidden party the bit shares
        // are structurally skipped, same as Mul.
        verify_party_view(&circuit, &all_ws[0], 0, &seeds[0].0, &tampered_aux, None).unwrap();
    }
}
